[project]
name = "starlette-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.23.3",
    "starlette>=0.50.0",
    "uvicorn>=0.38.0",
]
